# Generated by Django 3.1.3 on 2020-11-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_display',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
